### ISSUE TITLE
Get an error when posting pdf 

### ISSUE THREAD

**Issue by ibenhard** [L3-N0X/obsidian-marker#1]
`(task, pid=1465) INFO:     127.0.0.1:38582 - "POST /convert HTTP/1.1" 200 OK
(task, pid=1465) Could not determine filetype for b''`

When using terminal curl comand, everything works just fine (for the same pdf).

**Comment by L3-N0X** [comment]
The Error "Could not determine filetype for b'' comes up, when you push the "Test connection" button and it comes up, because the marker-api has no test or status endpoint, so the plugin just tries to convert an empty pdf (which obviously fails, but could still  be used to determine if the endpoint is working)
I just don't had a better solution for this connection check.

However, converting PDFs inside of obsidian should work without problems. When it also doesn't work for you when you try to convert a real pdf, please share your console  logs of obsidian so I can have a look.
It could also help to use localhost instead of the IP and trying another port.
Do you run the marker-api in docker? Are you running obsidian on windows?

**Comment by L3-N0X** [comment]
Never mind, I reinstalled from the community plugins page and got the same error, I try to fix it asap

**Comment by ibenhard** [comment]
I mean it's an ok solution for testing :) However, when right clicking (a PDF) and selecting "Convert PDF to MD" I get a "Connection successful" message in the top right corner of obsidian. The console in obsidian does not show any messages from your plugin. 

![image](https://github.com/user-attachments/assets/cdd7841b-126f-4874-962b-4190e9e7dd76)

**Comment by ibenhard** [comment]
I think the problem is here:

`	async onload() {
		await this.loadSettings();
		this.addCommands();
		this.addSettingTab(new MarkerSettingTab(this.app, this));
		this.registerEvent(
			this.app.workspace.on('file-menu', (menu, file, source) => {
				if (!file.name.endsWith('.pdf')) {
					return;
				}
				menu.addItem((item) => {
					item.setIcon('pdf-file');
					item.setTitle('Convert PDF to MD');
					item.onClick(async () => {
						if (file instanceof TFile) {
							await this.convertPDFToMD(file);
						}
					});
				});
			})
		);
	}`

You are sending it "file" onClick. One should think it's fine given that you are checking to se if its a TFile.
However, as the result is an empty string - I think it exit's in the first check you do in the fucntion convertPDFToMD - as file is not the atcivefile? Though its strange as you just declare the variable above the check.  + the folders never get created - so my best guess its here the problem is -  as it seams that whatever is passed to the fucntion is empty. It's difficult with no error message. 

`private async convertPDFToMD(file: TFile): Promise<boolean> {
		const activeFile = file;
		if (!activeFile) {
			return false;
		}`

**Comment by L3-N0X** [comment]
Fixed in 1.1.4, please update

**Comment by ibenhard** [comment]
Cool - works fine now :) What was the issue?

**Comment by L3-N0X** [comment]
Great! 

The testConnection function returned false all the time because the request was not async so it never waited for a response by the API. I changed it to return a promise and now it works. But I don't know why it worked when I tested the plugin. 
I also added back the empty script.css because there was an error about this file by obsidian when loading the plugin.
